a=float(input("enter the value of a:"))
b=float(input("enter the value of b:"))
add=a+b
sub=a-b
mul=a*b
div=a/b
print("addition=",add)
print("subtraction=",sub)
print("multiplication=",mul)
print("division=",div)
